title: Otacilio P S Filho # your name (or website title) here
logo: "/attachment/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 <h2>Data Engineer</h2>
  <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="light" data-type="VERTICAL" data-vanity="otacilio-psf" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://pl.linkedin.com/in/otacilio-psf?trk=profile-badge">Otacilio P S Filho</a></div>
  <a href="https://github.com/otacilio-psf" target="_blank"><img height="26" src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white" target="_blank"></a>
theme: jekyll-theme-minimal
